config/routes.rb
Rails.application.routes.draw do
  root "post#index"
  resources :post do
    resources :comments
  end
  devise_for :users

  get "/bottomtext", to: "meme#bottomtext"
  get "/isabella", to: "meme#isabella"
  get "/home", to: "post#index", as: "home_page"

  get "/profile/:id", to: "profile#show", as: "show_profile"
  get "/profile", to: "profile#index", as: "user_profile"

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/image.rb
class ImageValidator < ActiveModel::Validator
  def validate(image)
    if Image.exists?(url: image.url)
      image.errors[:url] << 'This image url is already in use'
    end
  end
end

class Image < ApplicationRecord
  # associations

  belongs_to :imageable, polymorphic: true

  # validations

  validates :url, presence: true, length: { minimum: 3, maximum: 254 }
  validates_with ImageValidator
end

app/models/post.rb
class PostValidator < ActiveModel::Validator
  def validate(post)
    unless !post.images.empty? || (post.content)
      post.errors[:content] << 'Needs either content or an image to be a valid post'
    end
  end
end

class Post < ApplicationRecord
  # associations

  has_many :posts_tags, dependent: :destroy
  has_many :tags, through: :posts_tags
  has_many :comments

  belongs_to :user

  has_many :images, as: :imageable

  # validations

  validates :user_id, presence: true
  validates_with PostValidator
end

app/models/posts_tag.rb
class PostsTagValidator < ActiveModel::Validator
  def validate(posttag)
    unless Post.exists?(posttag.post_id)
      posttag.errors[:post_id] << "Tries to link to a post that doesn't exist"
      return false
    end

    unless Tag.exists?(posttag.tag_id)
      posttag.errors[:tag_id] << "Tries to link to a tag that doesn't exist"
      return false
    end

  end
end

class PostsTag < ApplicationRecord
  # associations

  belongs_to :post
  belongs_to :tag

  # validations

  validates :post_id, presence: true
  validates :tag_id, presence: true
  validates_with PostsTagValidator
end

app/models/tag.rb
class Tag < ApplicationRecord

  # associations

  has_many :posts_tags
  has_many :posts, through: :posts_tags

  # validations

  validates :tag, presence: true, length: { maximum: 20 }
end

app/models/user.rb
class UserValidator < ActiveModel::Validator
  def validate(user)
    if User.find_by(username: user.username)
      user.errors[:username] << 'Username already exists'
    end
  end
end

class User < ApplicationRecord
  include ActiveModel::Validations  
  attr_writer :login


  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable, authentication_keys: [:login]

  # associations

  has_many :posts
  has_many :images, as: :imageable
  has_many :comments

  # validations

  validates :username, presence: true
  validates :status, presence: true
  validates :email, presence: true, length: { minimum: 4, maximum: 254 }
  validates :status, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates_with UserValidator
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  # methods 

  def login
    @login || self.username || self.email
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        new_comment = current_user.comments.new(comment_params)
        new_comment.post_id = params[:post_id]
        if new_comment.save
            redirect_to new_comment.post
        else
            render new_comment.post
        end
    end

    def show
        @comment = Comment.find(params[:id])
    end

    def destroy
        Comment.find(params[:id]).destroy
        redirect_to post_path(params[:post_id])
    end

    def update
        comment = Comment.find(params[:id])
        if comment.update(comment_params)
          redirect_to comment.post
        else
          render 'show'
        end
    end

    private
        def comment_params
            params.require(:comment).permit(:comment)
        end
end

app/controllers/meme_controller.rb
class MemeController < ApplicationController
    def bottomtext
    end
    def isabella
    end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  before_action :authenticate_user!
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def create
    new_post = current_user.posts.new(post_params)
    if new_post.save
      redirect_to new_post
    else
      render 'index'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    if post.update(post_params)
      redirect_to post
    else
      render 'edit'
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to home_page_path
  end

  private
    def post_params
      params.require(:post).permit(:content)
    end

end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @posts = current_user.posts
    end

    def show
        @user = User.find(params[:id])
        if @user == current_user
            redirect_to user_profile_url
        end
        @posts = @user.posts
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/meme_helper.rb
module MemeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/comments/show.html.erb
<%= form_with scope: :comment, model: @comment, local: true, url: post_comment_path(@comment), method: :patch do |f| %>
  <%= f.label :comment %>
  <%= f.text_area :comment, size: "40x2" %>
  <%= f.submit "Edit comment" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nowater Guwop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Boostrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/meme/bottomtext.html.erb
<style>
.bottomtext {
    width: 100vw;
    height: 80vh;
    display: flex;
    align-items: flex-end;
    justify-content: center;
    font-size: xx-large;
}
</style>

<div class = "bottomtext">
    <p>bottomtext</p>
</div>

app/views/meme/isabella.html.erb
<p>Holy fucking shit. I want to bang the animal crossing dog so goddamn bad. I can't stand it anymore. Every time I go to the town hall I get a massive erection. I've seen literally every rule 34 post there is of her online. My dreams are nothing but constant fucking sex with Isabelle. I'm sick of waking up every morning with six nuts in my boxers and knowing that those are nuts that should've been busted inside of Isabelle's tight dog pussy. I want her to have my mutant human/dog babies.

Fuck, my fucking mom caught me with the neighbors dog. I'd dressed her in my sister's skirt and went to fucking town. She hasn't said a word to me in 10 hours and I'm worried she's gonna take away my 3DS. I might not ever get to see Isabelle again.</p>

app/views/post/edit.html.erb
<%= form_with scope: :post, model: @post, local: true, url: post_path(@post), method: :patch do |f| %>
  <%= f.label :content %>
  <%= f.text_area :content, size: "40x2" %>
  <%= f.submit "Edit post" %>
<% end %>

app/views/post/index.html.erb
<%= render 'shared/nav', title: "Homepage"  %>
<div class="container">
	<div class="row justify-content-center">
		<div class = "card col-lg-10">
			<%= form_with scope: :post, local: true, url: "/post" do |f| %>
				<%= f.label :content %>
				<%= f.text_area :content, size: "40x2" %>
				<%= f.submit "Post" %>
			<% end %>
		</div>
	</div>

	<div class="row justify-content-center">
		<%= render 'shared/post',  style: 'col-10'%>
	</div>
</div>

app/views/post/show.html.erb
<%= render 'shared/nav', title: "post" %>

<p><%= link_to "#{@post.user.username}", show_profile_path(@post.user) %>
<%= @post.content %></p>
<p><%= link_to "back", :back  %></p>

<%= form_with scope: :comment, local: true, url: post_comments_url(@post) do |f| %>
  <%= f.label :comment %>
  <%= f.text_area :comment, size: "40x2" %>
  <%= f.submit "Comment" %>
<% end %>

<%= render 'shared/comment' %>

app/views/shared/_comment.html.erb
<h3>Comments:</h3>
<% @comments.all.each do |comment| %>
    <p><%= link_to "#{comment.user.username}", show_profile_path(comment.user) %>
    <%= comment.comment %>

    <% if comment.user == current_user %>
        <%= link_to "edit", [comment.post, comment] %>
        <%= link_to "delete", [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %></p>

<% end %>

app/views/shared/_nav.html.erb
<div id="navbar" class="navbar fixed-top navbar-light">
  <div>
    <span id='home'><%= link_to 'home', home_page_path %></span>
    <span id='profile'><%= link_to 'profile', user_profile_path %></span>
  </div>
  <h1 id='page-title' class="header"><%= title %></h1>
  <span id='logout'><%= link_to 'logout', destroy_user_session_path, method: :delete %></span>
</div>

app/views/shared/_post.html.erb
<% @posts.all.each do |post| %>
	<div id="post" class ="card <%=style%>">
	<!-- Post Content --->
		<div id="content">
			<p><%= post.content %></p>
		</div>
		<!-- Post Associations --->
		<div id="attribute">
			<p><%= link_to "#{post.user.username}", show_profile_path(post.user) %>
				<%= link_to "Show", post_path(post) %>
				<% if post.user == current_user %>
				<%= link_to "edit", edit_post_path(post) %>
				<%= link_to "delete", post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %>
				<% end %></p>
		</div>
	</div>
<% end %>

app/views/users/shared/_error_messages.html.erb
<div class="container">
  <div id="login-cont" class="card">
    <% if resource.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= I18n.t("errors.messages.not_saved",
                    count: resource.errors.count,
                    resource: resource.class.model_name.human.downcase)
          %>
        </h2>
        <ul>
          <% resource.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/users/shared/_links.html.erb
<div class="container">
  <div id="login-cont" class="card">
    <%- if controller_name != 'sessions' %>
      <%= link_to "Log in", new_session_path(resource_name) %><br />
    <% end %>

    <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
      <%= link_to "Sign up", new_registration_path(resource_name) %><br />
    <% end %>

    <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
      <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
    <% end %>

    <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
      <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
    <% end %>

    <%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
      <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
    <% end %>

    <%- if devise_mapping.omniauthable? %>
      <%- resource_class.omniauth_providers.each do |provider| %>
        <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
      <% end %>
    <% end %>
  </div>
</div>